### ISSUE TITLE
No Way to 'Listen' to Context/Store Changes in Another Component/Function

### ISSUE THREAD

**Issue by propkitty** [icsaba/lit-element-context#4]
App.tsx:
`context.init({theme: "dark"});`

Footer.tsx:
`context.setProp('theme', 'light');`

`this.requestUpdate("theme", oldValue);`

`updated(changedProperties: Map<string, unknown>){`

       `if (changedProperties.has("theme")){`

            `this.logoTheme = context.state['theme'];`

       ` }`

   ` }`

This is what I ended up having to do in order to make it so my footer lit-element would listen to the context being changed at all, so that in the render, I could change things related to the theme.

However, no other component I need to change things in for the theme can 'hear' the change happening and update along with the footer. Even getting the footer to 'hear' the change seemed more complicated than necessary. Setting a property in footer to the context.state['theme'] or anything else would trigger a re-render, either, even though the context was successfully changing. 

Let's say in my header, I need to know that the context.state['theme'] has been updated so I can cause it to re-render as well... except I can't. Unless there is something I'm missing, there is a badly needed connection here so changes within the context are known easily.

Perhaps something like:

var updated = context.updated;

updated would be an object that holds what had updated and the new value, pushed out on context changes, almost like updated in the lit-elements themselves.

**Comment by icsaba** [comment]
if i understand well, the problem is that, you didn't connect the element to the context. You should use `context.connect(...)` and `fromContext: true`  in the props in every component where you need the value.

**Comment by propkitty** [comment]
If I use the code listed:

myLitComponent.tsx:

`window.customElements.define('my-lit-component', context.connect(MyLitComponent));`

App.tsx:

`import '@elements/myLitComponent';`

I consistently get the error: 

`Property 'my-lit-component' does not exist on type 'JSX.IntrinsicElements'.`

I've been having to use the following to register the Lit Element to the JSX.IntrinsicElements:

myLitComponent.tsx:

`type CustomEvents<K extends string> = { [key in K] : (event: CustomEvent) => void };
type CustomElement<T> = Partial<T & DOMAttributes<T> & { children: any }>;
declare global {
    namespace JSX {
        interface IntrinsicElements {
            ['my-lit-component']: CustomElement<MyLitComponent>;
        }
    }
}
@customElement('my-lit-component')`


Edit:

Ah, but I can combine the two! Removing the @customElement('mylit-component') and putting the `window.customElements.define('my-lit-component', context.connect(MyLitComponent));` at the bottom of the page, there is success!

That helped immensely. Thanks!

**Comment by icsaba** [comment]
np, never tried it with typescript, i will figure out how to support annotations.

**Comment by icsaba** [comment]
I added TS support, you can connect your component to the context and subscribe for property changes:

```js
@customElement('my-element')
@context.connectElement()
export class MyElement extends LitElement {
  @property({fromContext: true})
  propFromContext = '';
}
```
